### ISSUE TITLE
insert: TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by wsjwa** [SpoonX/wetland#244] opened 2018-07-30 11:32 UTC
The error occurred in MYSQL(MariaDB) and Sqllite so far. Didn't test other Databases.

If you have a table with no autoincrement, you will get the error everytime you persist data in the table.

The data is successfully written, but you will get the error anyway.

Error: TypeError: Cannot convert undefined or null to object

**Comment by RWOverdijk** [comment] 2018-07-30 11:35
@wsjwa That's because it is looking for a primary key that's not set. It uses refresh and has no support for custom primary keys yet.

**Comment by wsjwa** [comment] 2018-07-30 11:41
So wetland does not support tables without autoincrement?

The table has a primary key. Just no autoincrement.

**Comment by RWOverdijk** [comment] 2018-07-30 11:44
I misunderstood then. It doesn't support custom relations with primary keys that aren't `id`. It's a feature being worked on.

Could you share the line-number of the error?

**Comment by wsjwa** [comment] 2018-07-31 08:37
Sure this is the error that gets thrown for an insert into a mysql table with primary key but without autoincrement option.

`
TypeError: Cannot convert undefined or null to object
    at Function.getOwnPropertyNames (<anonymous>)
    at Hydrator.fromSchema (C:\current_typescript\bugtests\node_modules\wetland\dist\src\Hydrator.js:35:16)
    at refresh.getRepository.getQueryBuilder.where.limit.getQuery.execute.then.freshData (C:\current_typescript\bugtests\node_modules\wetland\dist\src\Scope.js:109:45)
    at tryCatcher (C:\current_typescript\bugtests\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\current_typescript\bugtests\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\current_typescript\bugtests\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\current_typescript\bugtests\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\current_typescript\bugtests\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\current_typescript\bugtests\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\current_typescript\bugtests\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\current_typescript\bugtests\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
`

**Comment by wsjwa** [comment] 2018-07-31 08:40
Table:
`
CREATE TABLE `test` (
  `id` int(11) NOT NULL,
  `name` text COLLATE utf8_bin NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

ALTER TABLE `test` ADD PRIMARY KEY (`id`);
`

**Comment by RWOverdijk** [comment] 2018-07-31 08:52
That makes sense actually. Without looking into the code, it's trying to refresh your entity. But it can't, because there's no id being returned, because you're not using AI.

So you have two options (+ 1 bonus option):

1. Make the field AI.
2. Disable the refresh.

Bonus: make a PR with a nicer error message, explaining that a refresh isn't possible without a returned reference.

It's not a bug, it's a feature. 😄 But it's a poorly communicated feature.

`Scope.refresh()` is where it's at. This needs to check if the entity you're trying to resolve has a primary key value or not. If it doesn't, it shouldn't even try and throw an Error explaining why.

I hope this answers your question. If you want to pick up the bonus, that'd be great! It's a really small change so it might be a nice way to get in to the project. :)

**Comment by wsjwa** [comment] 2018-07-31 08:56
Ok thanks, good to know. :)
So refresh is an entity callback like beforeCreate()?

**Comment by RWOverdijk** [comment] 2018-07-31 09:16
Refresh is a Unit Of Work concept. It gets called on the scope when enabled. Every update or insert does a select after being committed to the database so that your in-memory data matches that of the database (think default values and triggers on your db side).

Right now you can only disable it globally, meaning that there's a change that your data is out of sync after running commit. If you use API driven dev and never refresh the data, it's safe to disable and will actually give you a rather decent performance boost.

**Comment by RWOverdijk** [comment] 2018-07-31 09:41
Another nice addition could be the option to disable refresh per-commit.

**Comment by wsjwa** [comment] 2018-07-31 12:01
i see. I'll have to look into Unit of Work. But i don't think i want to turnit off genrally. I still have other tables with an autoincrement. So a workaround is in order :) 
Have a nice day.

**Comment by RWOverdijk** [comment] 2018-07-31 14:06
@wsjwa It'll be done sooner rather than later. I find it shameful to see the error message the way it is.

```
  233 passing (2s)
  1 failing

  1) Scope .refresh() should throw an error on refresh without PK:
     TypeError: Cannot convert undefined or null to object
      at Function.getOwnPropertyNames (<anonymous>)
      at Hydrator.fromSchema (dist/src/Hydrator.js:35:16)
      at refresh.getRepository.getQueryBuilder.where.limit.getQuery.execute.then.freshData (dist/src/Scope.js:109:45)
      at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:512:31)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:569:18)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:614:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:693:18)
      at Async._drainQueue (node_modules/bluebird/js/release/async.js:133:16)
      at Async._drainQueues (node_modules/bluebird/js/release/async.js:143:10)
      at Immediate.Async.drainQueues [as _onImmediate] (node_modules/bluebird/js/release/async.js:17:14)
```

Working on it now.

**Comment by RWOverdijk** [comment] 2018-08-02 09:20
@wsjwa Just in case you missed the PR: can you take a look at #246 ?

**Closed** 2018-08-09 14:58 UTC
